spring:
  application:
    name: AgentX
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:agentx}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 跨域配置
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

server:
  port: 8080
  servlet:
    context-path: /api

# LLM服务配置
llm:
  provider:
    default: ${LLM_DEFAULT_PROVIDER:siliconflow}
    providers:
      siliconflow:
        name: SiliconFlow
        api-url: ${SILICONFLOW_API_URL:https://api.siliconflow.cn/v1/chat/completions}
        api-key: ${SILICONFLOW_API_KEY:}
        model: ${SILICONFLOW_MODEL:Qwen/Qwen3-32B}
        timeout: ${SILICONFLOW_TIMEOUT:30000}


# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.xiaoguai.agentx.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    type-handlers-package: com.xiaoguai.agentx.infrastrcture.converter
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted_at
      logic-delete-value: now()
      logic-not-delete-value: "null"
    banner: false


logging:
  level:
    org.springframework.web: DEBUG