version: "3"

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: agentx-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agentx
    ports:
      - "5432:5432"
    volumes:
      - ../docs/sql:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agentx"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    name: agentx-postgres-data
